### ISSUE TITLE
First Login issue

### ISSUE THREAD

**Issue by minimalchaos** [marcantondahmen/automad#1]
Hi,

For some reason I cannot login with the temporary user. Returns me back to the login page. Any suggestions ?

Fixed that and now :
```
2019/09/17 10:47:28 [error] 22399#22399: *4783 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /var/www/miniml.dev/public/automad/gui/themelist.php on line 103
PHP message: PHP Fatal error:  Call to undefined function Automad\Core\imagecreatefrompng() in /var/www/miniml.dev/public/automad/core/image.php on line 305" while reading response header from upstream
```
fix for second line was php-gd. However first I have no clue.

**Comment by marcantondahmen** [comment]
Hi, 

as I understand there are three issues and you fixed one already? The first error basically says, that one of the package subdirectories is not readable. Maybe there is an issue with permissions. I will take a closer look at this and maybe find a better and more safe way to check for installed packages.  

So maybe after checking the permissions, your initial problem is also resolved.

**Comment by minimalchaos** [comment]
I am unable to resolve the first line in the 2 line log statement

**Comment by marcantondahmen** [comment]
Hey, sorry for the late reply. I think the latest release from today will fix this issue.

**Comment by minimalchaos** [comment]
> Hey, sorry for the late reply. I think the latest release from today will fix this issue.

late is an understatement. but are you still supporting this project?
