### ISSUE TITLE
Possible XSS at login-area from dashboard

### ISSUE THREAD

**Issue by andresesam** [marcantondahmen/automad#10]
Hi, I've found a possible vulnerability in the login area in the current version of Automad's dashboard. The function automad-notify can be executed manually e.g. via the developer console. The problem is that the input is not sanitized and therefore any JavaScript code can be executed. Of course, this applies to all areas of the application where access to this function is possible. Enclosed a screenshot.

![xss_automad_notify](https://user-images.githubusercontent.com/39090774/84590746-71923e80-ae39-11ea-9657-b7c990a7c13b.png)

Best regards

**Comment by marcantondahmen** [comment]
Hi there, thanks for reporting this. Could you elaborate more on this? The notify functions actually never use any user input. The fact that you can use it from within the console is not more dangerous than running non-sanitized input directly in the console 🧐. As far as I can see it, it is important that those functions never use any kind of non-sanitized values of posted forms or manipulated URLs to prevent XSS attacks.

**Comment by andresesam** [comment]
Hi sure you are right of course, because the executed code is not stored persistently and is only reflected, an attack scenario is rather unlikely, nevertheless I wanted to share the scenario. I would still recommend to validate the input of the function

**Comment by marcantondahmen** [comment]
Hi, I will close this one here in favor of issue #11.
