### ISSUE TITLE
[v2,bug] href values are being generated incorrectly, resulting in broken links

### ISSUE THREAD

**Issue by ivorgri** [marcantondahmen/automad#104]
I was really looking forward to using v2, and seeing as I have a new side project, wanted to give it a whirl. So I started and noticed something odd happening in regards to hrefs to internal files (although I have also seen it work in other cases). 

Steps to reproduce:
- Navigate to https://dev.twilightimperium.nl (has the latest version unzipped - https://github.com/automadcms/automad-dist/archive/refs/heads/master.zip)
- Hover over the button that reads "DOWNLOAD IMAGE" - notice the URL reads: https://dev.twilightimperium.nl/pages/packages/automad/standard-v1/dist/automad-logo.png
- In the template file (templates/post.php), I have hardcoded the following: 
`<a href="packages/automad/standard-v1/dist/automad-logo.png">DOWNLOAD IMAGE</a>`
- So it seems that Automad is adding the "pages" part. If you access the URL directly (https://dev.twilightimperium.nl/packages/automad/standard-v1/dist/automad-logo.png), you should directly get the image. So I know the actual link is working
- You can also see the behavior on the "Visit dashboard link" (which orginally made me aware of the issue on my actualy dev site): you can see it adds "index.php" to the URL. This results in https://dev.twilightimperium.nl/index.php/dashboard. 

So it seems when you add relative links, the generated links are not correct. I have not noticed this behavior in v1, so I suspect that this has been introduced in v2. If I have missed anything that I would need to do differently in templates, I apologize. If you need more information, please do not hesitate to ask!

**Comment by ivorgri** [comment]
Oh wow, I didn't actually add the relative link... I could swear I did, but you are completely right... sorry for wasting your time... 

If anybody wants to know, the information for the linking can be found here: https://automad.org/user-guide/linking-to-files-and-pages.

**Comment by marcantondahmen** [comment]
No problem!
