### ISSUE TITLE
[v2, bug] pasting copied text in MD editor field is lightgray

### ISSUE THREAD

**Issue by anderer** [marcantondahmen/automad#113]
when i paste text in the MD editor in the content area, the text is lightgray before a lightgray background - thus not readable, the error is here in the CSS

.am-f-codeflask .codeflask__textarea

**Comment by marcantondahmen** [comment]
Hi, the error was due to overflowing text not being rendered at all. The grey on grey is only the underlying textarea that should be invisible. 

CodeFlask seems to have issues with overflowing text. The latest release fixed this by enabling text wrap instead of scrolling horizontally.
