### ISSUE TITLE
[v2, bug] Percentage does not work in block padding

### ISSUE THREAD

**Issue by Imerion** [marcantondahmen/automad#119]
Hi! I am currently testing alpha 8 of Automad 2.0 for a new project and I am amazed at how good it is. Fantastic work!
I have encountered a small bug that I thought was a good idea to report. When editing the padding of a block, using a percentage doesn't work. If I try to set a percentage it will instead be set to blank after confirming, looking like this:

![Padding](https://github.com/user-attachments/assets/bd93d145-fe88-4a6e-a833-05e07a75ae1d)

**Comment by marcantondahmen** [comment]
Hi, thanks for reporting. It will be fixed with the next release.

**Comment by Imerion** [comment]
Awesome, thanks!

**Comment by marcantondahmen** [comment]
Should be fixed now.

**Comment by Imerion** [comment]
Great, thanks!
