### ISSUE TITLE
Localized chars in theme.json

### ISSUE THREAD

**Issue by Every0ne** [marcantondahmen/automad#18]
Some localized chars in strings from _tooltips_ in _theme.json_ are shown as HTML entities in browser. For instance:
```
"tooltips": {
	"text_Naglowek": "Nagłówek"
}
```
is shown in dashboard as **Nagł&amp;oacute;wek** . This conversion is neither necessary nor consistent, as not all chars get converted - Ą, Ć, Ę, Ł, Ń, Ś, Ź, Ż remain unaffected.

**Comment by marcantondahmen** [comment]
Hi, thanks for reporting this. You're right that the conversion is really not needed anymore in the latest version. I removed it. The fix is already included in the latest release from today.
