### ISSUE TITLE
[Request Not an Issue] Include Language switcher snippet and examples by default

### ISSUE THREAD

**Issue by foxnoodles** [marcantondahmen/automad#24]
Pretty much what title says, the documentation is not quite beginner friendly and Multi Language support is something that a lot of  people will look after. It would be nice to make a package that does that or include the multi lang support in your current themes. Along with a clear basic tutorial on how to create hierarchy for multi lingual sites. Current example is simply not clear enough as it does not explain how the dashboard works with variables, where to add them, how to use them etc. and it also [IMO falsely] assumes that everyone knows how to tinker with Automad's themes. 

If it's not too hard to do please add it your feature backlog. 

Thank you and keep up the great work!

**Comment by marcantondahmen** [comment]
Hey there, I will put it on the list. 🙂 And btw there is no way of adding variables to the dashboard — the are added automatically as soon as they are used in a template. And of course any external tutorials are always more than welcome!

**Comment by foxnoodles** [comment]
Thanks!
