### ISSUE TITLE
Unused Variables - removing a variable does not trigger form change, save button remains inactive

### ISSUE THREAD

**Issue by coderars** [marcantondahmen/automad#26]
Hi @marcantondahmen!
Thank you for sharing this project, it looks very promising 👏 ! 
I'm just getting familiar with the system and during my tests, I found this little bug:

Pages / Page / "Data and Settings" form / Unused Variables / Remove (x)
The save icon in the top-right corner doesn't get active after removing a variable.

**Comment by marcantondahmen** [comment]
Thanks for reporting this! Will be fixed with the next release. 🙂

**Comment by marcantondahmen** [comment]
Fixed in version 1.8.0
