### ISSUE TITLE
Improvement(?): Make :current and :currentPath aware of directory redirects

### ISSUE THREAD

**Issue by marcoliverteschke** [marcantondahmen/automad#35]
Hi!

I just encountered an issue with a little experimental projects I'm doing with Automad.

This site has a two-level navigation structure, in which the first-level entries that have children themselves point to the first child.

So if I have

Parent
--Child1
--Child2

the menu entry for Parent will point to the url for Child1. Which I can easily do with the redirect field.

But, when I then switch to Child 2, the template variable :currentPath is no longer aware that we are still within Parent.

I've solved this by patching Page.php to prefer origUrl (if present) for setting :current and :currentPath.

[20211031-page-currentpath.diff.txt](https://github.com/marcantondahmen/automad/files/7449285/20211031-page-currentpath.diff.txt)

**Comment by marcantondahmen** [comment]
Thanks for reporting this! I will take a look at it.

**Comment by marcantondahmen** [comment]
Fixed with the latest release.
