### ISSUE TITLE
Cannot update user settings. Permissions denied: /app/config/accounts.php (Docker Installation)

### ISSUE THREAD

**Issue by BoredBrownBear** [marcantondahmen/automad#37]
Using latest Docker installation as of current date of posting, I can't update the user settings (i.e. change username, add email, change password, etc.)

Permissions denied:
/app/config/accounts.php

**Comment by marcantondahmen** [comment]
Hi, thanks for reporting this. Permissions are fixed now and the latest images are updated. Enjoy!
