### ISSUE TITLE
Pagelist not working

### ISSUE THREAD

**Issue by MazzMazz** [marcantondahmen/automad#38]
After a fresh install of automad 1.10.0 i noticed, that the "Tutorial" templates looked different in the editor.
I tried to add a Pagelist but an error is thrown in the Javascrip Console.

![image](https://user-images.githubusercontent.com/10706512/143498146-e661c924-4ba3-4789-863c-ae2e2d29a20e.png)

I installed a fresh Version 1.9.4 in which this Problem does not occur. It looks how i think it should look.

![image](https://user-images.githubusercontent.com/10706512/143498433-e5a374e6-53cc-4d74-bd36-80dc61f60b2c.png)

**Comment by MazzMazz** [comment]
After i updated the 1.9.4 installation to 1.10.0 it also breaks.

**Comment by marcantondahmen** [comment]
Hi, thank you for reporting this. I just released a patch.
