### ISSUE TITLE
Missing In-page edit buttons

### ISSUE THREAD

**Issue by 19wolf** [marcantondahmen/automad#4]
Hello,

I have a simple one page site but I'm missing edit buttons for most of my variables.

**Comment by marcantondahmen** [comment]
Hi,

I guess you are referring to the in-page edit mode. Without knowing the template in use it's difficult to identify the issue properly. The main purpose of in-page editing is to be able to quickly edit the main content of a page such as the title, date and text. In general, variables have no edit button in case they occur within an HTML tag's attribute, between an opening and closing anchor tag, within a control structure or statement, as a parameter of a pipe function and some other edge cases. All other variables should have an edit button.

**Comment by 19wolf** [comment]
Continuing discussion -> https://discuss.automad.org/d/117-missing-edit-links
