### ISSUE TITLE
Feeds need an optional base just like sitemaps do

### ISSUE THREAD

**Issue by michaellenaghan** [marcantondahmen/automad#57]
`Config.php` defines an "optional base protocol/domain combination for the sitemap.xml in case of being behind a proxy", [`AM_BASE_SITEMAP`](https://github.com/marcantondahmen/automad/blob/f631730deb600db7ee9086954943e6b111405f49/automad/src/Core/Config.php#L91).

It's used [here](https://github.com/marcantondahmen/automad/blob/f631730deb600db7ee9086954943e6b111405f49/automad/src/Core/Sitemap.php#L77).

Feeds need the same thing, for the same reason.

I'm not a PHP developer, but I am *a* developer. If you like I could tackle this over the next week, using the same approach that `Sitemap.php` takes? 

Let me know. 

If the answer is "yes," would you like to create a similar config var with a similar purpose? Or, somehow, one?

**Comment by michaellenaghan** [comment]
After thinking about this for a bit, I've come to the conclusion that there should really be one function (or one class or module) that generates all URLs.

Ultimately, I think there are three kinds. I'll call them "absolute URL"; "absolute path"; and "relative path." (I'm not sure Automad even deals in relative paths?) You'd tell the function which kind of URL you wanted (and what thing you wanted it for) and it would hand back the corresponding URL.

Absolute URLs would include the protocol; server name; and server port. I can't think of any reason you'd ever use, say, one server name in one place and a different server name in another. Not for the same server. So *all* absolute URLs would have to be "proxy aware."

It's the *kind* of URL that matters. How the URL is used — feed, sitemap, etc. — doesn't.

**Comment by marcantondahmen** [comment]
Already exists. Use the `AM_SERVER` constant to set a custom protocol and domain for feeds, the sitemap and other places.
The `AM_BASE_SITEMAP` can still be used alternatively and still exists for backwards compatibility.

**Comment by michaellenaghan** [comment]
Confirmed!
