### ISSUE TITLE
Content isn't being properly HTML/JS/XML encoded

### ISSUE THREAD

**Issue by michaellenaghan** [marcantondahmen/automad#58]
I added "<" and ">" around words in a lorem ipsum title:

    Ornare arcu odio ut <sem nulla> pharetra diam sit

The characters weren't properly encoded in the `<title>`, `<h1>`, etc. of the resulting HTML page (or the XML feed), e.g.:

    <title>My Site / Ornare arcu odio ut <sem nulla> pharetra "diam" sit</title>

Likewise, I added "<" and ">" around words in some lorem ipsum content:

    Amet mauris commodo quis imperdiet <massa> tincidunt.

The characters weren't properly encoded in the `<p>`, etc. of the resulting HTML page (or the XML feed), e.g.:

    <p class="am-block">Amet mauris commodo quis imperdiet <massa> tincidunt.</p>

Double-quotes are also a problem, because values aren't encoded when they're used in HTML attributes (e.g., the `content` val in a `<meta>` tag) or JSON (e.g., the `autocomplete` var in a `<script>` tag):

    <meta property="og:title" content="My Site / Ornare arcu odio ut <sem nulla> pharetra "diam" sit" />

This is a potential security issue; there are places where Automad accepts user input.

I've offered to help on the smaller items, but this one is above my current Automad abilities. I could, however, help with reviews.

**Comment by marcantondahmen** [comment]
Hi, thanks for reporting this. You're correct, HTML tags should be removed in that place. 

However, regarding the security issue I think it is only possible to compromise yourself since there is no public user input.

**Comment by michaellenaghan** [comment]
Not removed, encoded?

And just to make sure we're on the same page: you need two different kinds of encoding, HTML and JSON. The encoding rules are different. Because your JSON is being embedded in an HTML document, that snippet would first have to be JSON encoded and then HTML encoded.

**Comment by michaellenaghan** [comment]
> However, regarding the security issue I think it is only possible to compromise yourself since there is no public user input.

That's not true.

[Here](https://github.com/marcantondahmen/automad/blob/dff5972edf04c435b853e573259021a4f6fc198d/packages/standard/templates/elements/filters.php#L4) you take user input, `?filter`, and embed it directly into the page:

```php
    <@ if @{ ?filter } ~@>
        @{ ?filter }
    <@~ else ~@>
```

[Here](https://github.com/marcantondahmen/automad/blob/dff5972edf04c435b853e573259021a4f6fc198d/packages/standard/templates/elements/clear_search.php#L3) you take user input, `?search`, and embed it directly into the page:

```php
    @{ labelClearSearch | def('Clear Search Results for') } "@{ ?search }"
```

At the moment you're being saved by the call to `htmlspecialchars` here:

```php
    public static function query(string $key) {
        if (isset($_GET[$key])) {
            return htmlspecialchars($_GET[$key]);
        } else {
	    return '';
        }
    }
```

Should there be a corresponding call here?

```php
    public static function post(string $key) {
        if (isset($_POST[$key])) {
            return $_POST[$key];
        } else {
            return '';
        }
    }
```

Why? Why not?

Should you be escaping on input or on output? 

There has to be an underlying model — what's safe? what isn't? — and it has to be used consistently. Where security is concerned, it should also be checked.

Come to think of it, did you know that `htmlspecialchars` [has to be used correctly](https://odan.github.io/2017/01/02/how-to-use-htmlspecialchars-in-php.html)?

Security, like every other kind of "quality", can't be added after the fact. It has to be designed in.

I remember listening once to an interview with a convicted burglar. He said that when he broke into houses he found it easy to find the things that people were trying to hide, because they *thought like people who were trying to hide things*. Burglars can do that too. He said they should have been thinking like burglars instead.

You have incredible aesthetic sense. You pay attention to so many details. You have a lot of ideas that I, at least, haven't seen before — and I've seen a lot of things like this. For whatever reason, though, you don't treat security the same way.

Here's my little rant. 

The essence of engineering is preventing failure. To prevent failure, you first have to anticipate it. If you can anticipate it, and if it's a form of failure you care about, you have to take steps to prevent it.

You, as the developer, are the last line of defence for your users. Your users can choose to be less security conscious than you — but they can't ultimately be *more* security conscious than you. Because there are choices you make they can't do anything about.

I was able to demonstrate that, with the `.htaccess` file you ship with, I could access all kinds of files in your demo sites. I was able to demonstrate that I could execute files you didn't think would be executed through the browser. I was able to demonstrate how I, as a user, could close those particular holes. 

The problem is that I, as a user, can't fix the kinds of problems I've described here.

And you're not thinking like a burglar.

**Comment by michaellenaghan** [comment]
> Why? Why not? Should you be escaping on input or on output?

Rather than leaving those questions hanging, I'll answer them. I'll provide a simple model, and suggest an implementation that achieves that model.

The proposed model is this:

 * All content inside Automad is unencoded
 * Content is encoded at the point of use — because that's when you know what kind of encoding is required

Under that proposal, encoding input — as you're doing with your `GET` parameters — is wrong, and not encoding input — as you're doing with your `POST` parameters — is right.

Encoding is only meaningful in a particular context. For example, in HTML entities you have to encode `<` as `&lt;`, and you don't really have to encode quotes (though you can). In HTML attributes, you *do* have to encode quotes — as `&quot;`***. In JSON you also have to encode quotes — but the encoding is different: `\"`.

Sometimes you have to encode more than once. As I said, you currently have a JSON string inside HTML (at least in your Baker theme) — so you have to JSON encode first, and then HTML encode the result.*** You have to encode in that order because the browser will decode in the reverse order — HTML first, and then JSON. (Given what the browser will do, encoding HTML first, and then JSON, would produce the wrong result. Can you see why?)

With that, we can dive into why the current approach creates problems.

First, you'll end up using the HTML encoded input in contexts that don't expect encoding. For example, you're HTML encoding the user's search string. If the user searches for `"This & That"` or `"1 < 2"`, your current approach will fail to find matches — because your backend will *actually* be searching for `"This &amp; That"` or `"1 &lt; 2"`.

Second, the current HTML encoding is working only because you're using the encoded value in HTML. What if you embedded the value in JSON? What if you embedded it in JSON that was then embedded in HTML? What if you embedded it in a text file? In all of those cases the result would be wrong.

Third, you need a path to fixing this problem. The fix will mean encoding a lot of content that you aren't currently encoding. The easy and obvious path to a solution would mean it would be all too easy to encode your already encoded value. That would also be wrong.

So: the content in Automad should be unencoded, and you should encode at the point of use — when you know the context. How to do that?

I'll suggest something that I think will work — and it leverages the fact that you're using your own template engine.

 * First, give your template engine knowledge of the kind of output it's producing. Three obvious types are text (no encoding); HTML; JSON.

 * Second, for each kind of output, create a function that encodes and a function that decodes.

 * Third, when encoding for a particular kind of output, encode user values with the proper encoding by default.

 * Fourth, add a mechanism that avoids the default encoding (or a filter that undoes — i.e., decodes — the default encoding).

That approach would leave you safe by default, and it would mean that a mistake would result in *double-*encoding rather than *no-*encoding. Double-encoding would still be a bug, but it would be a safe bug.

To expand on that a bit: your template engine would *not* encode snippets at the point of use; at that point you'd assume that the value was already encoded. The point is not "encode everything always." But inside the snippet you'd encode any user values.

So here for example:

```
<@ if not @{ checkboxHideTitle } ~@>
    <h1 class="am-block uk-margin-bottom-remove uk-margin-top-remove"    
        @{ title }
    </h1>	
    <div class="am-block uk-margin-top-remove uk-margin-bottom">
        <@ subtitle.php @>
    </div>
<@~ end @>
```

`title` would be encoded by default, and `subtitle.php` would not.

You're not trying to catch errors in the templates themselves, you're trying to block holes created by using user values in the templates.

---

*** `htmlspecialchars` isn't doing that by default, so the result is not safe to use in HTML attributes. Even if you fixed that, though, you'd still have a problem if you embedded the result in, say, JSON.

*** You're only running into this problem because you've tried to hand-roll your own JSON. If you had used PHP's built-in JSON encoder it would have already done the JSON encoding for you, leaving you with just the HTML encoding problem. You should use PHP's built-in encoder; there are yet other issues that your hand-rolled version will run into.

**Comment by marcantondahmen** [comment]
> I was able to demonstrate that I could execute files you didn't think would be executed through the browser.

Where did you exactly demonstrate that? And which files are you talking about? This is a very bold claim you make here. 

Just to be clear here in case other users come across here, **accessing PHP source files is not possible**, accessing tests gives you just a blank page for obvious reasons, accessing Javascript source files or templates is irrelevant. 

What you state is simply not true.

And please don't confuse the option syntax with JSON. It is just not the same, which is obvious when you look at it.
