### ISSUE TITLE
After file delete, file upload opens delete modal

### ISSUE THREAD

**Issue by ponderboy** [marcantondahmen/automad#7]
1. Select a file
![grafik](https://user-images.githubusercontent.com/5340556/76784637-49506080-67b4-11ea-9860-73062e4c13f5.png)

2. Delete the file
![grafik](https://user-images.githubusercontent.com/5340556/76784701-65ec9880-67b4-11ea-9ba7-ab6304799391.png)

3. Try upload file > browse files > shows the delete modal again (upload via drag'n drop works though)
![grafik](https://user-images.githubusercontent.com/5340556/76784798-90d6ec80-67b4-11ea-85a7-3b44c0def09d.png)

**Comment by ponderboy** [comment]
After switching to another page and returning, this issue was gone.

**Comment by marcantondahmen** [comment]
Thanks for reporting this! I’ll take a look at it.

**Comment by marcantondahmen** [comment]
Ok, I got it. It will be fixed with the next release.
