### ISSUE TITLE
Feature Request: Option to open link in new tab

### ISSUE THREAD

**Issue by robinloeffel** [marcantondahmen/automad#77]
I've just received a question from a freelance client of mine, whether it would be possible to make the CMS open a link in a Text Block in a new tab. I was kinda baffled this wasn't an option so far and would like to request this feature. Just a simple checkmark and a small help text “Open in new tab” would be absolutely sufficient!

**Comment by marcantondahmen** [comment]
It's now possible in version 2. The second alpha was released yesterday.

**Comment by robinloeffel** [comment]
Sweet, thanks!
