### ISSUE TITLE
"No main theme defined" error on scratch v2 installation.

### ISSUE THREAD

**Issue by LifeDreamer24** [marcantondahmen/automad#78]
When entering the automad v2 path:
![image](https://github.com/marcantondahmen/automad/assets/62817314/9305c442-d70d-4f68-964b-d4c45a9b1241)
When entrering the path with /dashboard at the end:
![image](https://github.com/marcantondahmen/automad/assets/62817314/e96e320d-6e95-4a2f-a8df-be4e502ebede)
Is it normal? Tested from scratch on local installation and remote installation.

**Comment by marcantondahmen** [comment]
As stated in the readme, v2 is work in progress and not supposed to be installed. Please follow the docs in order to install the latest release instead.
