### ISSUE TITLE
PageList sort by publication date

### ISSUE THREAD

**Issue by bricebou** [marcantondahmen/automad#83]
Hey,

I'm discovering Automad for a small website I realize for a small non profit organization and I find it great ! I'm looking forward the version 2 you are working on :)

I'm trying to use a PageList widget with the default theme as on this screenshot: 

![Screenshot 2023-08-31 at 14-51-43 L'association — Automad](https://github.com/marcantondahmen/automad/assets/1000213/a3936df1-b17e-4e29-aaec-7f1761f064a1)

I have a major issue : selected items aren't sorted based on their publication date (the one I choose in the post Page Settings menu) but on their creation date...
![automad](https://github.com/marcantondahmen/automad/assets/1000213/66877876-970c-4e22-9c46-54a11ebac0e6)

Any idea to solve this issue ?

Thanks in advance !

**Comment by marcantondahmen** [comment]
Hi, in your current configuration you are using `:date`. Use `date` instead to sort by the date that is defined manually in the page settings.

**Comment by bricebou** [comment]
Great, it works perfectly, thanks a lot !
