### ISSUE TITLE
automad/dist/blocks/main.bundle.css is not exists in release

### ISSUE THREAD

**Issue by yagizhankd** [marcantondahmen/automad#88]
![image](https://github.com/marcantondahmen/automad/assets/25562110/99cfa29f-b2a0-4037-af5f-6be58cf505cd)

**Comment by marcantondahmen** [comment]
How did you install? Did you read the installation guide?

**Comment by yagizhankd** [comment]
I installed [2.0.0-alpha.2] (https://github.com/marcantondahmen/automad/releases/tag/2.0.0-alpha.2) directly from relase and there is no css file. It might be inside gitignore. But I didn't have any problem when I uploaded it from https://automad.org/.

**Comment by marcantondahmen** [comment]
Ok, that zip only contains the source. The installation guide contains the link to the distribution bundle.
