### ISSUE TITLE
[QUESTION] placement or removal of copyright footer

### ISSUE THREAD

**Issue by jmcouffin** [marcantondahmen/automad#94]
Hi Anton, 
Nice work. Revitron and Automad are pretty cool projects.

Quick quesiton, how do you control this
![image](https://github.com/marcantondahmen/automad/assets/7872003/8a68628b-a951-4fdf-b073-43f324f1ada2)

~both the bottom pages links on the left and~ the (c) 2024 copyright notice on the right?

**Comment by marcantondahmen** [comment]
Hi, the copyright notice is generated by the theme. In this case I guess it is the default one. There is no setting to disable this. However it is quite straight forward to get rid of it by just deleting it from the template.

**Comment by jmcouffin** [comment]
Starting to get the hang of it

in /automad/packages/standard/templates/post.php

I can comment 
```
					<li class="uk-text-right uk-text-left-small">
						<a href="/">
							&copy; @{ :now | dateFormat('Y') } @{ sitename }
						</a>
					</li>
```

Thanks for your answer.
